<?php echo $header; ?>
<h1 style="background: url('view/image/license.png') no-repeat;">Step 1 - License</h1>
<div style="width: 100%; display: inline-block;">
	<div style="float: left; width: 569px;">
		<?php if ($error_warning) { ?>
		<div class="warning"><?php echo $error_warning; ?></div>
		<?php } ?>
		<div style="background: #F7F7F7; border: 1px solid #DDDDDD; padding: 10px; margin-bottom: 15px;">
			<div style="color: #333; height: 300px; width: 545px; border: 1px solid #CCC; background: #FFF; overflow-y: scroll;overflow-x:hidden;">
				<div style="padding: 5px;">
					<h3 style="text-align: center;">Terms & Conditions</h3>
					<p><b>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THE JSI WEB TOOLS SITE</b></p>
					<p>JSI Web Tools Legal Statement - Terms and Conditions of Use</p>
					<p><strong>INTRODUCTION</strong></p>
					<p>Welcome to the Internet site of JSI Web Tools (referred to as the &quot;Site&quot;).</p>
					<p>By using the JSI Web Tools Site, or any of the products or services (collectively the &quot;Services&quot;) available on the Site, you agree, without limitation or qualification, to be bound by these terms and conditions and such other additional or alternative terms, conditions, rules and policies which are displayed or to which you may be directed in connection with any particular JSI Web Tools Site or Service, all as may be modified by JSI Web Tools from time to time in its sole discretion (collectively the &quot;Terms and Conditions&quot;). If you do not agree with these Terms and Conditions, you may not use the JSI Web Tools Site or any of the Services on the JSI Web Tools Site.</p>
					<p>We reserve the right, at our discretion, to change, modify, add, or remove portions of these terms and conditions of use at any time. Please check these terms and conditions of use periodically for changes. Your continued use of this Site following the posting of changes to these terms and conditions of use constitutes your acceptance of those changes.</p>
					<p><strong>PRIVACY</strong></p>
					<p>The use of this Site is subject to the JSI Web Tools Online Privacy Statement which forms part of these terms and conditions of use.</p>
					<p><strong>TRADEMARKS AND COPYRIGHTS</strong></p>
					<p>All software downloaded from JSIWebTools.com must keep the link in the footer &quot;Powered by JSI Web Tools&quot; and a link to <u><a>www.jsiwebtools.com</a></u>. Removal of this link will void the license.</p>
					<p>The license you are granted is for one website only. You may not use this software on multiple sites. You may not copy the site and give to nay other person or company </span></p>
					<p>All of the names, titles, logos, and designs on this Site identifying our products and brands, including any derivative and related names, titles, logos and designs, are trademarks and the sole and exclusive property of JSI Web Tools. All other names, titles, logos and designs appearing on this Site are the property of their respective owners. Any use of any trademarks appearing on the Site or any of the Services without the express written consent of the owner of the trademark is strictly prohibited.</p>
					<p>This Site contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, photographs, graphics, images, illustrations, audio, video and software (collectively, the &quot;Material&quot;) and the entire contents of this Site also are protected by copyright as a collective work and/or compilation under the Canadian copyright laws, international conventions and other copyright laws. We own the copyright in the Material original to us and in our selection, coordination, arrangement and enhancement of the Material.</p>
					<p>No Material may be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way without our express written consent. The use of any Material on any other web site is prohibited.</p>
					<p><strong>REGISTRATION, ACCOUNTS AND PASSWORDS</strong></p>
					<p>There is no cost to become a registered user of Straight.com and you do not have to become a registered user to use this Website. However, if you do not register, you may be precluded from using certain products, offerings, features or resources as offered at various times.</p>
					<p>As a registered user, you agree to provide true, accurate and complete information about yourself (&quot;Registered User Data&quot;) and to maintain and promptly update the Registered User Data to keep it accurate. Without limiting any other provision of these Terms &amp; Conditions, if you provide any information that is untrue, inaccurate, or incomplete, or we have reasonable grounds to suspect that such is the case, we reserve the right to suspend or terminate your user account and refuse any and all current or future use of our website (or any portion thereof).</p>
					<p>You agree not to assign, transfer or sublicense your rights as a registered user of this website.</p>
					<p>As a registered user, you also agree to be responsible for maintaining the confidentiality of any passwords or other account identifiers which you choose or are assigned as a result of any registration and as well as all activities that occur, including transaction effected, under such password or account. Further, you agree to notify the administrator of this website of any unauthorized use of your password or account. The owners of this website will not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with these provisions.</p>
					<p><strong>USER CONDUCT</strong></p>
					<p>You acknowledge that all content and all information, software, photos, video, text, graphics, music, sounds, questions, creative suggestions, messages, comments, feedback, ideas, recipes, notes, drawings, articles and other materials posted, emailed, or otherwise transmitted to or on this website, whether posted at our request or voluntarily, and whether publicly posted or privately transmitted (collectively, the &quot;Postings&quot;), are the sole responsibility of the person who made such Postings. This means that you are solely responsible for all Postings that you post, email or otherwise transmit to this website. We do not control the Postings posted, emailed or otherwise transmitted on our website by others and, as such, we do not guarantee the accuracy, integrity or quality of such Postings. Although we have adopted community standards and conduct guidelines for the users of our website (as described below), you understand that by using this website, you may be exposed to Postings that are offensive or objectionable. Under no circumstances will we be liable in any way for any Postings (other than for content developed by us), including, but not limited to, any errors or omissions in any Postings, or for any loss or damage of any kind incurred as a result of the use of any Postings posted, emailed or otherwise transmitted to or through this Website.</p>
					<p><strong>CONDUCT GUIDELINES</strong></p>
					<p>You agree not to use this Website to: </p>
					<p>(i) Upload, post, email or otherwise transmit any Postings or other materials that are unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libellous, invasive of another&#39;s privacy, hateful, or racially, ethnically or otherwise objectionable (in our sole discretion); </p>
					<p>(ii) Harm minors in any way; </p>
					<p>(iii) Impersonate any person or entity, including, but not limited to, a director, officer, employee, shareholder, agent or representative of Straight.com, our affiliates or any other person or entity, or falsely state or otherwise misrepresent your affiliation with Straight.com, our affiliates or any other person or entity; </p>
					<p>(iv) Forge headers or otherwise manipulate identifiers in order to disguise the origin of any materials transmitted to or through this website; </p>
					<p>(v) Upload, post, email or otherwise transmit any Postings or other materials that you do not have a right to upload, post, email or otherwise transmit under any law or under contractual or fiduciary relationships (such as insider information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); </p>
					<p>(vi) Upload, post, email or otherwise transmit any Postings or other materials that infringe upon any patent, trade-mark, trade secret, copyright, industrial design, right of privacy or publicity or other intellectual property or proprietary rights of any party; </p>
					<p>(vii) Upload, post, email or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, &quot;junk mail,&quot; &quot;spam,&quot; &quot;chain letters,&quot; &quot;pyramid schemes,&quot; or any other form of commercial solicitation, except in those areas of this Website, if any, that are specifically designated for such purpose;</p>
					<p>(viii) Upload, post, email or otherwise transmit any Postings or other materials that contain software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; </p>
					<p>(ix) Interfere with or disrupt this Website or servers or networks connected to this Website, or disobey any requirements, procedures, policies or regulations of networks connected to the Website; </p>
					<p>(x) Intentionally or unintentionally violate any applicable local, provincial, state, national or international law, including, but not limited to, any regulations having the force of law; </p>
					<p>(xi) &quot;Stalk&quot; or otherwise harass another user of this Website or employee of Straight.com or our affiliates; or</p>
					<p>(xii) Collect or store personal data or attempt to collect or store personal data about other users of the Website. </p>
					<p><strong>RIGHT TO REVOKE PRIVILEGES</strong></p>
					<p>Your privilege to contribute to discussions on this website depends on your compliance with the community standards and conduct guidelines set forth above. We may revoke your privileges to use all or a portion of this website and/or take any other appropriate measures to enforce these community standards and conduct guidelines if violations are brought to our attention. Further, if you fail to adhere to our community standards and conduct guidelines, we may terminate, in our sole discretion, your use of, or participation in, discussions on this website. </p>
					<p>All website communications including, but not limited to, comments, chat and message board communications, are public and not private communications. We reserve the right to monitor some, all, or no areas of this website for adherence to the community standards and conduct guidelines set forth above or for any other purpose. You acknowledge that by providing you with the ability to distribute Postings, we are acting as a passive conduit for such distribution and we are not undertaking any obligation or liability relating to any Postings or activities on this website. Although we reserve the right to remove, without notice, any posting for any reason, we have no obligation to delete Postings that you may find objectionable or offensive.</p>
					<p><strong>LINKED WEB SITES</strong></p>
					<p>Please exercise discretion while browsing the Internet. As a service to visitors to this Site, we may include links may take you to other websites over which we have no control. These sites are independent from JSI Web Tools and we do not endorse, control or make any representations, warranties or conditions concerning their contents or links. If you decide to visit any linked site, you do so at your own risk and it is your responsibility to take all protective measures to guard against viruses and other destructive elements.</p>
					<p>We reserve the right to disable links to and from this Site.</p>
					<p><strong>DISCLAIMER AND LIMITATION OF LIABILITY</strong></p>
					<p>THIS SITE AND THE INFORMATION OR MATERIALS CONTAINED THEREIN ARE PROVIDED &quot;AS IS&quot; WITHOUT ANY REPRESENTATIONS, WARRANTIES OR COVENANTS OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. WE DO NOT WARRANT THAT THIS SITE OR THE SERVERS THAT MAKE MATERIAL AVAILABLE WILL BE OPERABLE, UNINTERRUPTED, VIRUS FREE OR ERROR FREE, OR THAT DEFECTS WILL BE FOUND OR CORRECTED. WE ALSO DO PROVIDE NO WARRANTY REGARDING THE ACCURACY, TIMELINESS, AUTHENTICITY, COMPLETENESS OR RELIABILITY OF ANY INFORMATION, CONTENT, SERVICE OR OTHER MERCHANDISE PROVIDED THROUGH THIS SITE.</p>
					<p>YOU ACKNOWLEDGE AND EXPRESSLY AGREE THAT USE OF THIS SITE IS AT YOUR SOLE RISK AND DISCRETION. YOU AGREE TO INDEMNIFY US AND HOLD US AND OUR DIRECTORS, OFFICERS, EMPLOYEES, AGENTS AND REPRESENTATIVES ABSOLUTELY HARMLESS FROM ANY CLAIM ARISING FROM OR IN ANY WAY CONNECTED TO YOUR USE OF THIS SITE, INCLUDING YOUR POSTING, UPLOADING OR SUBMITTING MATERIALS OR CONTENT TO ANY FORUM OR TO THIS SITE OR YOUR FAILURE TO COMPLY WITH THESE TERMS AND CONDITIONS OF USE. IN NO EVENT WILL WE OR OUR DIRECTORS, OFFICERS, EMPLOYEES, AGENTS AND REPRESENTATIVES BE LIABLE TO ANY PARTY UNDER ANY CIRCUMSTANCES FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR LOST PROFITS THAT RESULT FROM YOUR USE OF, OR YOUR INABILITY TO USE, THIS SITE OR MATERIALS OR FUNCTIONS ON THIS SITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN TORT, NEGLIGENCE, STATUTE, CONTRACT, COMMON LAW, EQUITY OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU TO US, IF ANY, FOR ACCESSING THIS SITE.</p>
					<p><strong>GOVERNING LAW AND JURISDICTION</strong></p>
					<p>This Site is controlled by us from our offices within the Province of Ontario, Canada. We make no representation that materials on this Site are appropriate or available for use in any particular location. Those who choose to visit and use this Site do so on their own initiative and are responsible for compliance with all applicable laws.</p>
					<p>These terms and conditions of use shall be governed by and construed in accordance with the laws of the Province of Ontario, without regard or giving effect to any principles of conflicts of law. You agree that any action at law or in equity arising out of or relating to these terms and conditions of use shall be filed only in the provincial or federal courts located in Toronto, Ontario, and you hereby consent and submit to the exclusive personal jurisdiction of such courts for the purposes of litigating any such action. If any provision of these terms and conditions of use shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these terms and conditions of use and shall not affect the validity and enforceability of any remaining provisions. This is the entire agreement between us relating to the subject matter herein and shall not be modified except in writing, signed by both parties.</p>
					<p>English shall be the language of this Site and all transactions occurring in connection with this Site. The parties waive any right to use and rely upon any other language, or translations. Il est de la volont&eacute; express des parties que le pr&eacute;sent site et tous les affairs qui s&#39;y rapportent soient r&eacute;dig&eacute;s en langue anglaise, exception faite des documents pour lesquels la loi exige l&#39;usage exclusif du fran&ccedil;ais.</p>
					<p><strong>ARBITRATION AND ACTIONS</strong></p>
					<p>Any controversy, claim or dispute arising out of or relating to these Terms and Conditions, your use of the JSI Web Tools Site or Service or the relationship which results from these Terms and Conditions, including without limitation, the performance, breach, enforcement, existence or validity of the matters provided for in these Terms and Conditions which cannot be amicably resolved, even if only one of the parties declares that there is a difference (collectively, a &quot;Claim&quot;), will be referred to and finally settled (to the exclusion of the courts) by private and confidential binding arbitration before a single arbitrator held in Toronto, Ontario in English and governed by Ontario law. The arbitrator shall be a person who is legally trained and who has experience in the information technology field in Canada and is independent of either party. Any such Claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim, controversy or dispute of any other party. You agree to waive any right you may have to commence or participate in any class action against us related to any Claim and, where applicable, you also agree to opt out of any class proceedings against us. Notwithstanding the foregoing, we reserve the right to pursue the protection of intellectual property rights and confidential information through injunctive or other equitable relief through the courts.</p>
					<p><strong>RESPONSIBILITY FOR MINORS</strong></p>
					<p>In cases where you have authorized a minor to use the JSI Web Tools Site or any of the Services, you recognize that you are fully responsible for: (i) the online conduct of such minor; (ii) controlling the minor&#39;s access to and use of the JSI Web Tools Site or any of the Services; and (iii) the consequences of any misuse by the minor. You acknowledge that some of the areas of the JSI Web Tools Site may contain material that is inappropriate for minors.</p>
					<p><strong>PROFESSIONAL INFORMATION DISCLAIMER</strong></p>
					<p>The JSI Web Tools Site will not disclose any of your personal information to any one in any way. - for any reason.</span></p>
					<p><strong>SUBMISSION OF IDEAS AND/OR SUGGESTIONS</strong></p>
					<p>If you have ideas and/or suggestions regarding improvements or additions, JSI Web Tools will accept them - but any submission will be subject to these Terms and Conditions. UNDER NO CIRCUMSTANCES SHALL ANY DISCLOSURE OF ANY IDEA AND/OR SUGGESTION OR RELATED MATERIAL TO JSI WEB TOOLS BE SUBJECT TO ANY OBLIGATION OF CONFIDENTIALITY OR EXPECTATION OF COMPENSATION. BY SUBMITTING THE IDEA AND/OR SUGGESTION OR ANY RELATED MATERIAL TO JSI WEB TOOLS , YOU ARE WAIVING ANY AND ALL RIGHTS THAT YOU MAY HAVE IN THE IDEA AND/OR SUGGESTION OR ANY RELATED MATERIAL AND ARE REPRESENTING AND WARRANTING TO JSI WEB TOOLS THAT THE IDEA AND/OR SUGGESTION OR ANY RELATED MATERIAL ARE WHOLLY ORIGINAL WITH YOU, THAT NO ONE ELSE HAS ANY RIGHTS IN THE IDEA AND/OR SUGGESTION OR ANY RELATED MATERIAL AND THAT JSI WEB TOOLS IS FREE TO IMPLEMENT THE IDEA AND/OR SUGGESTION AND TO USE THE RELATED MATERIAL IF IT SO DESIRES, AS PROVIDED OR AS MODIFIED BY JSI WEB TOOLS , WITHOUT OBTAINING PERMISSION OR LICENSE FROM ANY THIRD PARTY.</p>
					<p><strong>GENERAL PROVISIONS</strong></p>
					<p>This agreement is personal to you, and you may not assign your rights or obligations to anyone. These Terms and Conditions constitute the entire agreement between JSI Web Tools and you pertaining to your use of the JSI Web Tools Site, Services and Content and supercede any prior agreements between you and JSI Web Tools with respect to the subject matter hereof. JSI Web Tools&#39;s failure to insist upon or enforce strict performance of any right or provision of these Terms and Conditions shall not constitute or be construed as a waiver of any right or provision. If any of the provisions (or parts thereof) contained in these Terms and Conditions are determined to be void, invalid or otherwise unenforceable by a court of competent jurisdiction, such determination shall not affect the remaining provisions (or parts thereof) contained herein. No changes to these Terms and Conditions shall be made except by a revised posting on this page or except as otherwise expressly contemplated herein. The parties have required that these Terms and Conditions and all documents relating thereto be drawn up in English. Les parties ont demand&eacute; que cette convention ainsi que tous les documents que s&#39;y rattachent soient r&eacute;dig&eacute;s en anglais.</p>
				</div>
			</div>
		</div>
		<form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form">
			<div style="background: #F7F7F7; border: 1px solid #DDDDDD; padding: 10px; margin-bottom: 15px; text-align: right;">I agree to the license
				<input type="checkbox" name="agree" />
			</div>
			<div style="text-align: right;"><a onclick="document.getElementById('form').submit()" class="button"><span class="button_left button_continue"></span><span class="button_middle">Continue</span><span class="button_right"></span></a></div>
		</form>
	</div>
	<div style="float: right; width: 205px; height: 400px; padding: 10px; color: #003366; border: 1px solid #CCE0FF; background: #CCF5FF;">
		<ul>
			<li><b>License</b></li>
			<li>Pre-Installation</li>
			<li>Configuration</li>
			<li>Finished</li>
		</ul>
	</div>
</div>
<?php echo $footer; ?>